### ISSUE TITLE
[15.0][project_stock] Error selecting type operation when any task is already created

### ISSUE THREAD

**Issue by Bilbonet** [OCA/project#1042]
## Module
project_stock

## Describe the bug
Error selecting type operation when any task is already created

## To Reproduce
**Affected versions**: 14.0

1. Create a new project
2. Create a new task for the project
3. Go to the project. In the stock section, select the picking operation type and save the change.

you get next error:

```
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/bilbonet/odoo15/server/odoo/http.py", line 643, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/bilbonet/odoo15/server/odoo/http.py", line 301, in _handle_exception
    raise exception.with_traceback(None) from new_cause
AttributeError: 'stock.location' object has no attribute 'get_warehouse'
```

**Comment by victoralmau** [comment]
The problem occurs in 15.0: https://github.com/OCA/project/pull/1046

**Comment by Bilbonet** [comment]
Yes, sorry.
The problem was in 15.0

Thanks !!!!
