### ISSUE TITLE
[14.0] project_timesheet_time_control on runboat: "No default view of type 'timeline' could be found !"

### ISSUE THREAD

**Issue by jcdrubay** [OCA/project#1045]
## Module
project_timesheet_time_control

## Describe the bug
When trying to open the task analysis menu, I get the error message "No default view of type 'timeline' could be found !"

![image](https://user-images.githubusercontent.com/1765420/206603952-a59a8756-d556-438b-8e83-95f9e4ce33cb.png)

![image](https://user-images.githubusercontent.com/1765420/206603847-3d7569a8-413c-46eb-9740-766d0d31b83d.png)

## To Reproduce
**Affected versions**:

tested with 14.0

**Expected behavior**

No error message

**Additional context**

Right now, can be reproduced at this URL: 
http://oca-project-14-0-57d650a6ef6b.runboat.odoo-community.org/web#action=464&model=project.profitability.report&view_type=pivot&cids=1&menu_id=188

**Comment by bodedra** [comment]
Probably a dependency issue. I think the "[web_timeline](https://github.com/OCA/web/tree/14.0/web_timeline)" module adds timeline type to the view.

**Comment by rmorant** [comment]
The action opened by Task Analysis menu is : 'project.action_project_task_user_tree'
This action is extended in project_timeline module with the timeline view mode, but there is no view defined for the 'report.project.task.user' model.
I fix this adding a view like this.
```xml
<record id="view_task_project_user_timeline" model="ir.ui.view">
        <field name="model">report.project.task.user</field>
        <field name="type">timeline</field>
        <field name="arch" type="xml">
            <timeline
                date_start="date_assign"
                date_stop="date_end"
                default_group_by="project_id"
                event_open_popup="true"
            >
            </timeline>
        </field>
    </record>
```

**Comment by moitabenfdz** [comment]
Solved in #1152

**Comment by zamberjo** [comment]
Hi @moitabenfdz  Can you also fix this in the next versions?

**Comment by moitabenfdz** [comment]
I'm on it.

**Comment by moitabenfdz** [comment]
PRs #1160 & #1161
