### ISSUE TITLE
[14.0] [Project Task Material] BUG when click on list

### ISSUE THREAD

**Issue by josepmy** [OCA/project#1142]
Install the module and go to a project task to add a material.
If you click on the list to select a material an error appears.

`Rastreo de error:
Error: value.split is not a function
_getDisplayName@https://demo.xxx.com/web/content/10216-b052f17/web.assets_backend.js:1104:101
_search/values<@https://demo.xxx.com/web/content/10216-b052f17/web.assets_backend.js:1109:287
_search@https://demo.xxx.com/web/content/10216-b052f17/web.assets_backend.js:1109:223`

**Comment by moitabenfdz** [comment]
Can't reproduce it. Can you provide more info about this, and all the steps you made to get this error?
