### ISSUE TITLE
[13.0] Link Supplier to task

### ISSUE THREAD

**Issue by JoanRibotAE** [OCA/project#1144]
Hello,

In my company we need to link a supplier (from the account module) with a task. Is there a module that accomplishes this functionality? I didn't find any.

If not, we would develop it ourselves. Would OCA be interested in us doing a pull request with this module if we develop it?

**Comment by leemannd** [comment]
Hello @JoanRibotAE I'm not sure there is a module doing it. If you want to contribut, every contribution is welcome
