### ISSUE TITLE
project_status in standard since 15.0 but ported in 15.0

### ISSUE THREAD

**Issue by remytms** [OCA/project#1269]
The module `project_status` brings statuses or stages on `project.project`. This has been added in standard (module `project`) since version 15.0 via [project.project.stage](https://github.com/odoo/odoo/blob/15.0/addons/project/models/project_project_stage.py).

The module `project_status` exists in 15.0 and seams to be refused into 16.0, see https://github.com/OCA/project/pull/1124.

This leads to difficulties form migrating database.

In OpenUpgrade, we can mark the module `project_status` as merged into `project`. The right place for doing that is in scripts in 15.0 version.

Doing the migration to standard in 15.0 is as simple as:
```python
if openupgrade.table_exists(env.cr, "project_status"):
    openupgrade.rename_tables(
        env.cr,
        [("project_status", "project_project_stage")],
    )
    openupgrade.rename_columns(
        env.cr,
        {
            "project_project_stage": [
                ("company_id", None),
                ("description", None),
                ("status_sequence", "sequence"),
                ("is_closed", None),
            ],
        },
    )
    openupgrade.rename_columns(
        env.cr,
        {
            "project_project": [
                ("project_status", "stage_id"),
            ],
        },
    )
```
This script is tested and works.

But what to do with database in 15.0 that does not use the standard stages but the module `project_status` ?

Another solution is to mark the module `project_status` as merged in version 16.0 in OpenUpgrade (which is not correct, but match the state of the this repository). Then the script for migrating data will be a bit more complicated because tables already exists since version 15.0 so we need to copy data from tables to tables and update references.

Or we can do both.

I don't know whats the best approach. Personally, I'm not in the case of using `project_status` in 15.0, so I'm in favor of the simplest solution: migrating in 15.0.

@patrickrwilson as maintainer of `project_status`.

@pedrobaeza @legalsylvain I ping you because it's related to OpenUpgrade.

**Comment by pedrobaeza** [comment]
You can add scripts in `project` module to detect if coming from a v14 having `project_status` installed and do whatever stuff you need.
