### ISSUE TITLE
16.0 project_key installation issue 

### ISSUE THREAD

**Issue by hspl-vegra** [OCA/project#1274]
step to reproduce: 
create a fresh database with demo data and try to install module. you will get the below error.

![image](https://github.com/OCA/project/assets/124571041/5a84d06d-33ae-4bd8-a67f-f1ea777b6564)

**Comment by ssoni-surekhatech** [comment]
@hspl-vegra Please look into this PR [1340](https://github.com/OCA/project/pull/1340)

**Comment by hspl-vegra** [comment]
> @hspl-vegra Please look into this PR [1340](https://github.com/OCA/project/pull/1340)

Yeah Sure
