### ISSUE TITLE
[8.0] project_task_materials_stock Error changing stage after consume materials

### ISSUE THREAD

**Issue by spalenzuela** [OCA/project#135]
I can not change the status of a task after consuming materials. It fires an exception: You can only delete draft moves.

**Comment by rafaelbn** [comment]
cc @sergio-incaser

**Comment by sergio-teruel** [comment]
@rafaelbn fixed in #145 . please review

**Comment by pedrobaeza** [comment]
#145 is merged, so I close this one.
