### ISSUE TITLE
Duplicate fields in project_timeline with Odoo Enterprise project_enterprise

### ISSUE THREAD

**Issue by tobru** [OCA/project#1362]
## Module

project_timeline

## Describe the bug

In c607eaa fields were renamed into fields which are already existing in `project_enterprise` from Odoo Enterprise.
This makes project_timeline incompatible with Odoo Enterprise.

```
psycopg2.errors.DuplicateColumn: column "planned_date_end" specified more than once
```

## To Reproduce
**Affected versions**: 16.0

1. Install Odoo Enterprise with `project_enterprise` 
2. Try to install `project_timeline`

**Expected behavior**
The addon `project_timeline` is compatible with Odoo Enterprise

**Comment by tobru** [comment]
@carlos-lopez-tecnativa Would you mind looking into that? This was introduced in recent commits you were involved in.

**Comment by pedrobaeza** [comment]
Yes, both modules are not intended to be installed together, and moreover, we can't care here about code that is not open. If you want to add the fix in a way that doesn't bring any damage on community version, it can be checked, but there isn't any other compatibility duty here.
