### ISSUE TITLE
[16.0] Project timesheet time control is not working expected

### ISSUE THREAD

**Issue by vaibhavtsd** [OCA/project#1384]
Once I install this module and try to run it will show an error **like 2 running timer found. Cannot know which one to stop. Please stop them manually.**

## Module
project_timesheet_time_control

## Describe the bug
Start Now functionality is not working

## To Reproduce
**Affected versions V16**:

Steps to produce the behavior:
1. Open Task 
2. Click on Start Workbutton

**Expected behavior**
If we start and stop in task via the button (Start Work) it should add time to timesheet 
![runboot](https://github.com/user-attachments/assets/2ab0cce5-dc40-4b3b-a561-9ea13cbdc601)

**Comment by pedrobaeza** [comment]
The error is clear: you have several timesheet entries with 0 time spent. Don't press on that button and create directly a line, or put an amount on the opened entries.

**Comment by vaibhavtsd** [comment]
I don't have several timesheets with 0 time spent. all the exacting timesheets entry with exact time still I am facing a issue.
