### ISSUE TITLE
[8.0][project_closing] Add functionality to delete analytic account when deleting project

### ISSUE THREAD

**Issue by rafaelbn** [OCA/project#148]
module: project_closing
version: 8.0

Hi all,

I would like to as if you agree or not.

Project manager have access to project
Project manager doesn't have access to accounting

Sometimes projects manager create projects that after all must be deleted because are not need anymore. This projects have analytic account (aa) but doesn't have task nor activities.

When project manager delete the project, aa is still there.

**Do you agree to improve functionality of this module to delete aa when its related project is deleted only in the case that aa doesn't have and journal?**

Thanks

**Comment by dreispt** [comment]
Sounds reasonable to me: AA and Project are excepcted to be a 1:1 relation.

**Comment by rafaelbn** [comment]
What do you think about this @pedrobaeza @antespi ?

**Comment by pedrobaeza** [comment]
OK for me too if there are no analytic entries for that AA

**Comment by rafaelbn** [comment]
Closing too old!
