### ISSUE TITLE
[8.0] project_task_code fail to load

### ISSUE THREAD

**Issue by syci** [OCA/project#160]
I view on log this WARNING:

openerp.modules.module: module project_task_code: no **openerp**.py file found

But the file is on folder. The perms are ok, ?¿?¿?

**Comment by pedrobaeza** [comment]
You should check your deployment (branch downloaded, for example), because the module works without problem.

**Comment by dreispt** [comment]
I confirmed that the CI tests are good: https://travis-ci.org/OCA/project/jobs/110529259#L1393-L1436
