### ISSUE TITLE
Shortcut to show communication or notes

### ISSUE THREAD

**Issue by fernandomr** [OCA/project#181]
Hi,

Add a shortcut in the kan ban view and in tree view that opens a wizard with the messages of message_ids component of project.issue. Almost like the behavior of the icon that opens mail editor on the same field (present on the form view). So users might not click on issue anymore to see the history of that specific item since I think the javascript loading will take more time than opening and closing a wizard.

It's actually a improvement that I think can help a lot in shorten time of issue or tasks attendance.

**Comment by dreispt** [comment]
What is the benefit compared to opening the Issue form view?

**Comment by fernandomr** [comment]
From my point of view, it's time saving since the javascript loading should take more time than just opening and closing a wizard.
I can relate to a recent experience... the client would send a issue report every time something not worked out as expected, and the issue may have a conversation running on that affects it's resolution. In a environment with high issue reporting on which the users have to be alert when the issue is registered, opening the form in each issue slows down the process.

**Comment by dreispt** [comment]
But I understand you are proposing to open a form window with the message history.
I don't see much improvement compared to opening a form with the message history and the issue info.
