### ISSUE TITLE
[Blueprint] Add Service Partner

### ISSUE THREAD

**Issue by dreispt** [OCA/project#189]
On service management use cases we can have Service Contracts, and for these you may want to identify the Service Items covered by the Contract.
### Current status

Currently the OCA/project already supports these concepts:
- **Service Contracts** are modeled as _Analytic Accounts_.
- **Service Items** can be represented as _child Analytic Accounts_.
- **Service Requests/Orders** can be represented either as _Project Tasks or Project Issues_.
- **Service Desks** are where the end users will place their requests. These are represented as _Projects_ and should have a user/customer oriented organization.
### The need

In non trivial setups we also need a Service Company or Department, identifying who should provide service on a Service Item or Contract. 
It's possible that this service is be outsourced to a supplier/business partner, or provided internally by an employee or department. Scenarios with both cases are not uncommon.
### Proposed design

I propose to **add to "Analytic Accounts" (thus to Service Items) a new "Service Partner" field**, linked to a Partner record. 

It can represent an external company or person, or an internal employee or team/department. 
In the last case we might need to artificially create a Partner record for the employee or team, but would be the price to pay to avoid a more complex design.

In the first case we may create several Contact Partners under the same parent Company Partner, to represent different branches or technical practices: 
- depending on the Service Item's address, in can be serviced by different branches/offices of the servicing company;
- depending on the Service Item's technology, it can be serviced by different specialist teams of the same servicing company.

Also adding a a "Is Service Provider" flag to Partners would make it much easier for service managers to maintain their Contracts mater data.

The Service Partner should be copied to the Service Request (issue or Task) when selection the Service Item, for auditing purposes and for enabling business rule automation, such as assigning responsible users or sending out notifications.
### Going further

With this we can assign a Service Partner individually to each Service Item, but that maintenance task could be simplified by using a matrix, to automatically pick  a Service Partner depending on Service Item attributes: geographical localization (Service Area), technical Type, and maybe others.

This is compatible and would extend the proposed design, but is out scope for this bleprint.

**Comment by pedrobaeza** [comment]
Maybe you can use https://github.com/OCA/account-analytic/tree/8.0/analytic_partner for this purpose.

**Comment by dreispt** [comment]
@pedrobaeza Thanks for your comment Pedro. AFAICS that module makes sure the AA's Partner is propagated to move lines, so that it is available for analysis.
The point here is to add a Service Partner, for operational management purposes, and not relevant for account moves.
