### ISSUE TITLE
Recurring invoices in contracts backport currency is always Euro

### ISSUE THREAD

**Issue by mohamedhagag** [OCA/project#19]
the recurring contracts backport have a bug - I think it's a bug - that it creates all invoices with currency set to Euro.

I tried this with many DBs and same result.

If i create invoices normally out of contracts I get the correct currency.

So only invoices generated by this module gets a fixed currency of Euro.

Some Details:
- OpenERP v. 7.0 latest stable build
- Module is account-analysis-recurring backport 
- DB is empty from scratch DB without demo data
- Invoiceing installed & configured with US CoA / Service based business + currency other than Euro.
- contracts and recurring backport installed

Regards,

**Comment by pedrobaeza** [comment]
Hi, Mohamed, thanks for the bug report. Indeed, there was a bug in the code, that I have fixed in #20. Please review the PR and see if it's working.

Regards.

**Comment by dreispt** [comment]
Closed by #20
