### ISSUE TITLE
 With all the rights I have: except_orm: (u'Access Denied', u'The requested operation cannot be completed due to security restrictions. Please contact your system administrator.\n\n(Document type: Project, Operation: create)')

### ISSUE THREAD

**Issue by VbossEkat** [OCA/project#190]
Good afternoon!
I have all the necessary rights .
But when I try to create a project , I get the error :
except_orm: (u'Access Denied ', u'The requested operation can not be completed due to security restrictions Please contact your system administrator \ n \ n (Document type:.. Project, Operation: create)')
Creating a project is only possible by the user admin.
Please, help.

**Comment by pedrobaeza** [comment]
With what modules installed? If it's only standard modules, this is not the right place to put the issue, but odoo/odoo.

**Comment by dreispt** [comment]
@VbossEkat please provide the steps to reproducr on OCA Runbot. Was that with the `admin` user?
