### ISSUE TITLE
Create tasks from RMA

### ISSUE THREAD

**Issue by rubencabrera** [OCA/project#200]
I am working on a module to create and link tasks from RMA claims and I was thinking about also taking into account materials for deliveries and possibly repairs.

RMAs are related to pickings, but the module project_task_materials_stock links to moves, so any ideas on how to make it simple are welcome. 

The materials to add to the task would be the products in outgoing pickings (checking with self.env.ref('stock.picking_type_out').id).

I have to improve the code quite a bit but I'm already working on the PR I'll soon link.

Thanks for any help or opinion you might add here!

**Comment by dreispt** [comment]
Task Materials are to be expended in the task execution, and are not meant to be directly linked to deliveries or sale orders. And products are expected to be consumed by the task.
IMO you might be better off adding something alongside Task Materials, since the workflow and logic will probably be quite different.

Maybe @pedrobaeza can add some more input here.

**Comment by rubencabrera** [comment]
Hello, @dreispt, 

It makes sense to keep task materials limited to the current use. RMA deliveries wouldn't be included in tasks and tasks would be limited to the job of repairing some already sold products. 

I'll throw in some more details in case it helps.
When handling RMAs and post sale claims, it's common to solve them through a repair of the product. Sales orders related to this service are already handled through RMAs, so thinking of it, this might be the proper way to go and no changes would be necessary to task materials.

Maybe some more details about the related sales in the RMA form view would be useful, as this is might be a common way for companies of generating leads and the main aim of starting this conversation is having a good an efficient way of handling claims and converting them to well organized tasks when necessary. 

Thanks a lot for your input!
