### ISSUE TITLE
Project_GTD project.task.copy_data does hard overwrite of defaults instead of checking

### ISSUE THREAD

**Issue by ehirt** [OCA/project#210]
Should be: 
        if not default.get('timebox_id', False):    
            default['timebox_id'] = False
        if not default.get('context_id', False):    
            default['context_id'] = False

**Comment by ehirt** [comment]
change was tested on a 6.1 version installation

**Comment by dreispt** [comment]
Can you open a PR with your fix, please?

**Comment by ehirt** [comment]
closed in issue #211
