### ISSUE TITLE
[blueprint] [8.0] project need to have project.category specific for categorize business 

### ISSUE THREAD

**Issue by martintorresvm** [OCA/project#238]
On project_categ

Already have task_categ_id and mean to set a root Category for Tasks linked.

So on Task could choose only Tags which parent is the root Category on Project.

Our concern is to have one unique category on Project that mean to categorize for which kind of Operation is.

For this on 
project.categoy we think to add boolean is_business_category
add constrain to prevent have duplicated name if is_business_category

Add on project.project
project_category_id many2one project.category
On Form View: should be required
ACL to be discuss
Group by
Search

**Comment by martintorresvm** [comment]
@elicoidal Please have a check

**Comment by elicoidal** [comment]
@victormartinelicocorp if we have a specific field o2m, we don't need this do we? for the tags, we do not care much about duplication. Remember:
* Tags field are used for search and multi-classification
* Category field is used for statistics and mono-classification

**Comment by martintorresvm** [comment]
@elicoidal  ok then just might be need to modify the model project.category to add checkbox to manage special cases as we'll need on BR modules.

**Comment by elicoidal** [comment]
Yes

**Comment by dreispt** [comment]
Instead of a checkbox, I would instead use a "Root for Main Category" field, similar to what was done to with the Tags ("project_categ") module.
That will cover your use case, and is more flexible.
