### ISSUE TITLE
[8.0] project_categ and project_categ_issue both offer a way to categorize Projects

### ISSUE THREAD

**Issue by martintorresvm** [OCA/project#245]
For project managers that need to categorize different project for different purposes found that is installed both modules: 
project_categ and project_categ_issue both offer a way to categorize Projects.

Then, how to decide which one is more important in order to categorize?
Furthermore the string that user could read means that is the root category for Task and the other is for Issues. So is not the main purpose to categorize projects and none of them are mandatory on Project form.

My point is we should introduce a new model:
class_name `ProjectCategorySuper`
`_name='project.category.super'`
`_inherit='project.category'`

Then on Project add relation Many2One to ProjectCategorySuper 

And set as mandatory for any projects at the Form View level.
Also a good place to show such field could be after `partner_id`
And of course add search and group by.

**Comment by martintorresvm** [comment]
@elicoidal @seb-elico

**Comment by elicoidal** [comment]
I am not sure about the value: it seems to me to make it very complex.

**Comment by dreispt** [comment]
The goal for those modules is not to categorize Projects, but to limit the selectable Tags on Tasks and Issues to a specific domain.

I see unnecessary to add the extra model.
We could just add an additional Project Category field instead, but even so I don't think it's the best option.
Instead, you could just make the `parent_id` field available in the Project form.
It is an existing field inherited from Analytic Account.
This way, you could have a hierarchy tree of Projects.

**Comment by martintorresvm** [comment]
> The goal for those modules is not to categorize Projects, but to limit the selectable Tags on Tasks and Issues to a specific domain.

I totally agree and because of that I create this Issue.

> We could just add an additional Project Category field instead, but even so I don't think it's the best option.
Instead, you could just make the parent_id field available in the Project form.
It is an existing field inherited from Analytic Account.
This way, you could have a hierarchy tree of Projects.

@dreispt I admit that have hierarchy tree based on Projects parenting is a way to categorize.

But, don't you think could be handy to have an option to identify later on reports for which main and very general "purpose" is a Project and could group and filter independent from which parent comes? 

Also just to put as an inconvenience is the fact that parenting is deprecated since V9 if later migrate then our parenting and categorize just disappear. 

cc @elicoidal @seb-elico

**Comment by dreispt** [comment]
OK, I agree on adding a specific Category field to Projects.
If we also use a Category hierarchy, I see benefits in the implementation you suggested, I would just change the name from `project.category.super` to the more specific `project.category.project`.

I suggest to add that feature to the existing `project_categ` module.
The field should be optional. If you want it mandatory in your deployment, customize the view for your customer.
