### ISSUE TITLE
[10.0] project issue code 

### ISSUE THREAD

**Issue by m3dbedb** [OCA/project#246]
Module adds / sign to issue's header and uneditable ID field. In odoo 8 works nice
![is_code8](https://cloud.githubusercontent.com/assets/25632818/24550485/e6bd9c30-1626-11e7-977e-bd913ef946e3.PNG)

![is_code](https://cloud.githubusercontent.com/assets/25632818/24550335/34057d38-1626-11e7-8084-34334a5c6313.PNG)

**Comment by pedrobaeza** [comment]
See https://github.com/OCA/project/pull/244.
