### ISSUE TITLE
[10.0] project_task_materials  ParseError: "Error while validating constraint

### ISSUE THREAD

**Issue by m3dbedb** [OCA/project#247]
Error while installing module
`  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\models.py", line 1074, in _validate_fields
ParseError: "Error while validating constraint

Element '<field name="work_ids">' cannot be located in parent view

Error context:
View `project.task.form.materials`
[view_id: 1049, xml_id: n/a, model: project.task, parent_id: 499]
None" while parsing file:///c:/Program%20Files%20(x86)/Odoo%2010.0/server/custom/project_task_materials/views/project_view.xml:5, near
<record id="view_project_task_form_materials" model="ir.ui.view">
      <field name="name">project.task.form.materials</field>
      <field name="model">project.task</field>
      <field name="inherit_id" ref="project.view_task_form2"/>
      <field name="arch" type="xml">

        <field position="after" name="work_ids">
          
          <field name="material_ids" groups="project.group_tasks_work_on_tasks">
            <tree string="Materials used" editable="top">
              <field name="product_id"/>
              <field name="quantity"/>
            </tree>
          </field>
        </field>

      </field>
    </record>`

**Comment by pedrobaeza** [comment]
The module is not yet migrated, so normal that it throws error if you force its installation changing the installable flag.
