### ISSUE TITLE
[10.0] project_model_task - depends on Sample Project and installs demo data even without demo database configuration

### ISSUE THREAD

**Issue by bistaray** [OCA/project#248]
I had to modify the manifest - my database isn't configured for demo data (so I don't want demo data unless it is) and I have deleted the Odoo Sample Project.

Don't need any action, just reporting.

**Comment by dreispt** [comment]
Confirmed, needs to be fixed: https://github.com/OCA/project/blob/10.0/project_model_to_task/__manifest__.py#L16

**Comment by dreispt** [comment]
Fixed by #249
