### ISSUE TITLE
[RFC] Maintenance Plans 

### ISSUE THREAD

**Issue by dreispt** [OCA/project#263]
We have Contracts (Analytic Account) that include Corrective and Preventive maintenance services.

I would like to be able to define generic Maintenance Plans, and on each Contract define what Maintenance Plan (many2one) to be used. 
At this point the Maintenance Plan structure required is quite simple: just set a period between services. For example: every 6 months, or every 12 months.

Basic Maintenance Plans:
- Add the "Maintenance Plan" model, defining a period between services: period type is "months" or "days"; period number is a float.
- Add to Contracts a "Maintenance Plan" many2one field.
-  Add to Contracts a "Next Service Date" allowing manual input.
- Add to Contracts  a "Last Service Date" for manual input, with an onchange to automatically compute the "Next Service Date" based on the Maintenance Plan period.

As an option, we could use Tasks to manage Preventive service:
- Add a "Template Service Task" many2one field to Maintenance Plans.
- Add a "Next Service Task" many2one to Contracts.
- When a Maintenance Plan is set on a Contract, the "Next Service Task" is generated from the template.
- The Contract "Next Service Date" is the Next Service Task Deadline Date (a non editable related field).
- Add a "Last Service Task" field to Contracts.
- When the "Next Service Task" is done, it is set as the "Last Service task", and a new "Next Service Task" is automatically generated.
- The Contract "Last Service Date" is the "Last Service Task" Deadline Date (a non editable related field).

**Comment by pedrobaeza** [comment]
Hi, Daniel, I think this should be attached to new maintenance module and hosted in the new repository that I'm going to create for that (I wrote about that request one week ago). We have some work done, but it's not linked to this. We have to polite it on the migration to version 10 (in progress). I will show you when done.

**Comment by dreispt** [comment]
I worry about the underlying master data structure: in this RFC is is Contract/Analytic Account, I've seen other implementations that don't suit me since they are based on company Assets.

I've also been doing some design work for ITIL support, and it also has an "Asset" concept, not related to accounting, but a "serviceable item".

I'm considering introducing the generic concept of "Service items", than can have a related company Asset or a (Contract) Analytic Account.
This would allow for generic maintenance features to cover all scenarios: our own machines; machines we rent to customers; and machines owned my customers.

Does this fit in your work?

**Comment by pedrobaeza** [comment]
What we have separate 2 things: the equipment and the maintenance contract. On the maintenance contract you specify which equipments and which tasks.

**Comment by dreispt** [comment]
Is the equipment an Asset, or a new Model?
Is the Maintenance Contract an Analytic Account?

**Comment by pedrobaeza** [comment]
In the module we have in v8, a new model. What I'm planning for migration is to use core model maintenance.equipment (https://github.com/odoo/odoo/blob/7413b2624c6554bf641c2426c45c70fd59bc7490/addons/maintenance/models/maintenance.py#L90).

**Comment by dreispt** [comment]
Can I have a peek at the current code? (I'm aware it's wip).

**Comment by dreispt** [comment]
Just took a look at 10.0 `maintenance` and it seems the right direction.
My work on this will probably target 10.0/11.0.

**Comment by pedrobaeza** [comment]
What are your deadlines? If you give me one week, I can draft the new module. For now, the v8 version is not disclosed as it has several conditionals. That's why I want to redo it on v10.

**Comment by dreispt** [comment]
OK, no problem - no short term deadlines here.
BTW, there is one thing about the Maintenance standard module: it mostly copies what Project Tasks do, and by doing it loses features - both standard (like timesheet integration) and from community extensions 😛

**Comment by pedrobaeza** [comment]
Well, I only want the base model. The rest will be done through tasks.

**Comment by dreispt** [comment]
Maybe we can add an automated link between Tasks and Maintenance Request, to leverage the maintenance features already there.

**Comment by pedrobaeza** [comment]
Yeah, it can be... I haven't done the analysis of that part yet.

**Comment by grindtildeath** [comment]
Hi
I'm actually developing a new module (v10) for a customer, which extends the preventive maintenance functionality on equipments in the new maintenance module. 
The goal is to allow different kinds of preventive maintenance on an equipment with a specific period and duration for each, while keeping the basic features (creation of next maintenance request through cron job after last maintenance request is done).
I could share the code quite easily if you guys are interested. (though it's not planned to integrate with contracts or projects yet).

**Comment by dreispt** [comment]
@grindtildeath Can you please share your code, even if it is a WIP?

**Comment by grindtildeath** [comment]
@dreispt Could use github down time to create the repo, so here it is : https://github.com/grindtildeath/maintenance

**Comment by dreispt** [comment]
@grindtildeath Thanks for sharing. You module supports more complex maintenance plans, and is a good complement for the standard module. You should consider contributing it to the OCA.

My focus here will be on a different (complementary) axis: to integrate the Maintenance module with Project Tasks, so that you can leverage on Maintenance Requests other features you already have for Tasks, such as Timesheets an Materials spent.

**Comment by lasley** [comment]
This RFC would help us internally 👍 

Something I see missing - we would need to define the project in which the maintenance plan tasks are created in. I think it would make sense to define this in the service task and template, although overrides at the contract level would be awesome.

**Comment by grindtildeath** [comment]
@dreispt Thanks for your comment. I will gladly share it to the OCA when a maintenance repository is created.
I also think having the ability to timesheet and add materials on maintenance.request would be great. Yet I haven't used the project module, so I don't know how it should interact.

**Comment by pedrobaeza** [comment]
I have created a new repository in https://github.com/OCA/maintenance for maintenance related modules.

**Comment by lasley** [comment]
@pedrobaeza - I think this repo may be a bit ambiguously named? To me, this repo would be dedicated to things regarding the maintainence of the Odoo instance itself (a subset of `server-tools` almost). 

The problem is, I can't think of a better name. `project-maintenance` maybe?

**Comment by pedrobaeza** [comment]
Yeah, I thought that also, but it's not only with project. Check my first PR submission, that has nothing to do. That's why I tried to put a correct explanation on the repository description. It also follows current main Odoo module name for managing equipments and their maintenance.

Any advise on this description although the repository name itself can lead to confusion? For me, such repository you mention would be _server-maintenance_.

**Comment by lasley** [comment]
> Check my first PR submission, that has nothing to do.

Yeah I saw this after my comment. I was going to say `maintenance-planning`, but I think even that doesn't quite nail it.

> Any advise on this description although the repository name itself can lead to confusion?

Let's see how it evolves and go from there. I figured the name itself is a big deal early on, but we can evolve the description pretty easily over time.

**Comment by dreispt** [comment]
Dave, the repo is to host maintenance management features, built around the `maintenance` core module. I think that `OCA/maintenance` is the right name for the repo.
