### ISSUE TITLE
[RFC] Project Status Overview

### ISSUE THREAD

**Issue by dreispt** [OCA/project#287]
As an IT Manager/Director, I need to oversee the status of my ongoing projects, in order to periodically report to stakeholders.

A key output is a grid with the active Projects, a very short status summary, and the progress over the X last reporting periods. 

At this point, "progress" can mean just a short free text description the stage/phase the project in.
Later improvements could make the current state a Many2one field, and add some KPIs (% complete, risk traffic-light sign) .

**Proposed design**

* Add to Projects a "Status" notebook tab, with  fields: Status Date, Status Summary and Status Description.
* Writing on these fields will trigger a write on a Project Status History table. If there is already a record for the Status Date, it will overwrite the existing data.
* A view bases model should be provided for dashboard/reporting purposes, mapping the status lines against a timeline (similarly to "project.task.cumulative").
* In the corresponding Pivot view, the user can choose the period of the reporting: monthly, weekly, daily...

**Comment by bistaray** [comment]
We have implemented something related.  In our case, stakeholders also ask "Why?" and suggest actions to be taken. We show Projects via the Kanban, grouped by Project Status. We added status, chatter and several informational fields on the Project. Users filter the Kanban as they "report" the status, relay questions from stakeholders via chatter, reassign the PM, create new tasks, etc. (all possible from a Kanban modeled on the Tasks Kanban)

**Comment by dreispt** [comment]
Nice! Is that work something you can share?

**Comment by bistaray** [comment]
Is it tightly coupled with business logic 'rules' associated with the movement of projects and the movement of paired opportunities.  Give me until the end of the week to see how much I can unbundle.  Can you use fragments of code and XML that offer up the main things we did?

**Comment by dreispt** [comment]
A version stripped down of all the business logic would be great.
Just looking at the data model would be useful to check it it is compatible with my needs.
If you could also get some XML, even if not clean, it would be great.

**Comment by bealdav** [comment]
:+1:
