### ISSUE TITLE
Issue Installing project_sla module

### ISSUE THREAD

**Issue by mmotahar** [OCA/project#29]
Hi,

We setup a new server environment and installed project module and then installed project_sla module. below are error messages we got.

In client: 

Invalid XML Architecture 

In Server:
2014-10-08 08:40:54,505 25073 INFO project_oca openerp.modules.loading: module project_sla: loading project_sla_view.xml
2014-10-08 08:40:54,538 25073 ERROR project_oca openerp.addons.base.ir.ir_ui_view: <string>:2:0:ERROR:RELAXNGV:RELAXNG_ERR_EXTRACONTENT: Element form has extra content: h1
2014-10-08 08:40:54,549 25073 ERROR project_oca openerp.tools.convert: Parse error in /opt/openerp/server/custom_modules/project_sla/project_sla_view.xml:21:
<record id="view_sla_form" model="ir.ui.view">
            <field name="name">view_sla_form</field>
            <field name="model">project.sla</field>
            <field name="arch" type="xml">

```
            <form string="SLA Definition">
              <h1>
                  <field name="name"/>
              </h1>
              <group>
                  <group>
                      <field name="control_model"/>
                      <field name="control_field_id"/>
                  </group>
                  <group>
                      <field name="active"/>
                  </group>
              </group>

              <notebook colspan="4">
                <page string="Rules" name="rules_page">
                  <field name="sla_line_ids" nolabel="1"/>
                </page>
                <page string="Contracts" name="contracts_page">
                  <field name="analytic_ids" nolabel="1"/>
                </page>
              </notebook>
              <button name="reapply_slas" colspan="2" string="Reapply SLA on Contracts" type="object"/>
            </form>

        </field>
    </record>
```

Thanks,

**Comment by dreispt** [comment]
My guess is that you're mixing up Server/Module major versions.
Make sure you've downloaded the module version  targeted at your server version.
`<h1>`is supported since v7, so I guess you're running v6.1, right?

**Comment by mmotahar** [comment]
No I am running version 7. However, I just checked the module versions and realized that the folder is upzipped with the name : project-service-8.0 so I think you are right problem seems to be for version.

I am downloading branch 7.0 again and copy the files to the addons.

Do I need to copy the "**unported**" folder to the addons as well? I am guessing not, but just wanted to make sure there is no reference to it from other modules and we are not hitting any errors.  Thanks

**Comment by dreispt** [comment]
The `__unported__` directory not used and is safe to delete. They are modules from previous version waiting for someone to port them to the new version.

**Comment by mmotahar** [comment]
Thanks for the information Daniel,
