### ISSUE TITLE
[10.0][RFC] Project Task Category unique 

### ISSUE THREAD

**Issue by martintorresvm** [OCA/project#312]
Have project.task link to unique category for statistic. 

Create new class: 
class ProjectCategory
_name: 'project.category'
_inherit: 'project.tags'

Inherit class:
class Task(models.Model):
_inherit = "project.task"

categ_id = Many2one('project.category')

Add menu to manage Category
Add on Form, Tree view, Search, Group by

Good to have: 
Demo data

**Comment by martintorresvm** [comment]
@elicoidal @seb-elico Please have a check.

**Comment by elicoidal** [comment]
:+1:
