### ISSUE TITLE
[10.0] Web timeline changes task kanban_state on move

### ISSUE THREAD

**Issue by D4N** [OCA/project#316]
Summary:
The web_timeline module changes the kanban_state of a task when the task is moved in the same stage (i.e. the date is changed but not dragged to a different stage).

How to reproduce:
Create a new task, set its kanban_state to anything **but** 'normal'. Switch to the timeline view and move the task to a different date, but keep the stage. Switch back to the kanban view and the task's kanban_state is now at 'normal', independently of its previous state.

Cause:
The underlying problem is that project_timeline causes the following api call on a date change (visible at the log level debug):
`odoo.api: call project.task(32,).write({u'date_end': u'2017-09-25 22:00:00', u'date_start': u'2017-09-24 22:00:00', u'stage_id': 1})`
This in itself is not a problem, the problem arises from the way project.task.write() is implemented: https://github.com/odoo/odoo/blob/10.0/addons/project/models/project.py#L516. Once stage_id is set in vals, the kanban_state is **always** set to normal. Thus also in this case, even when the stage_id was not changed.

Possible fix:
Either only set stage_id in the write call, if the stage_id was actually changed, or make upstream check their write function whether the stage is actually changed and only then change the kanban_state.

**Comment by pedrobaeza** [comment]
@JBF91 you made the last change over this. Maybe you can fix this. The involved line is:

https://github.com/OCA/web/commit/e17f516cc0591a4a6454c68cbfb8d00a64b1e6e4#diff-2f26223a1c994010d8f4d139c73b438dR410

but I'm not sure if we can detect what is the previous value to compare if there has been any change.

**Comment by D4N** [comment]
Wouldn't it be possible to query the current group_id via xml-rpc, and only add it to the write if it changes?

**Comment by simahawk** [comment]
outdated, feel free to reopen if needed

**Comment by D4N** [comment]
Simone Orsi <notifications@github.com> writes:

> outdated, feel free to reopen if needed

Nope.
