### ISSUE TITLE
[10.0] Project timeline, planning on the calendar

### ISSUE THREAD

**Issue by davinci41** [OCA/project#317]
Hello,

I would like to be able to schedule tasks by start time (date_start) and duration (planned_hours).
The usual calendar I mastered:
<calendar color="user_id" date_start="x_date_start" date_delay="planned_hours" string="Zadania" mode="day">
	<field name="project_id" on_change="1" can_create="true" can_write="true" modifiers="{}"/>
	<field name="name" modifiers="{'required': true}"/>
	<field name="user_id" on_change="1" can_create="true" can_write="true" modifiers="{}"/>
	<field name="stage_id" can_create="true" can_write="true" modifiers="{}"/>
</calendar>

I had to do the x_date_start field because the start_date field indicates the start date and assignment date (if I change user_id to date_start from scheduled it updates to the current time-  no sense)

results:

![image](https://user-images.githubusercontent.com/25403547/30613527-b526cb58-9d88-11e7-9cba-e4fd0a2f3b0d.png)
![image](https://user-images.githubusercontent.com/25403547/30613667-3d56fd18-9d89-11e7-8d59-d74c69657c56.png)

Well now, I would like to be able to plan and have an equivalent view in the timeline to the calendar view, but unfortunately the program does not allow the use of "date_delay" (planned_hours), why?

<timeline date_start="x_date_start" date_delay="planned_hours" default_group_by="project_id" event_open_popup="true" colors="#ec7063: user_id == false; #2ecb71: kanban_state == 'done';"/>

With this configuration, to use drop and drag and move the task I have this error:

![image](https://user-images.githubusercontent.com/25403547/30613873-e3c21be2-9d89-11e7-8a4e-815a547862f4.png)

Please help I am a beginner.

**Comment by pedrobaeza** [comment]
Implemented in https://github.com/OCA/web/pull/735
