### ISSUE TITLE
[10.0] Project Model to Task - Number of task created not updated in object form view

### ISSUE THREAD

**Issue by pgu42** [OCA/project#322]
Hello
I created a related task from a partner's form view (eg on the partnet Agrolait). 
On the form view of the task created, there is a link to the partner (Agrolait) in the field "Task Origin", but when i'm on the partner's form view (Agrolait), on the up right the number of tasks (related to this partner) is not updated and remains at zero.

![image](https://user-images.githubusercontent.com/15345051/30918969-66993624-a3a0-11e7-8584-4fce2edca653.png)

**Comment by dreispt** [comment]
I just tested this on Runbot and it worked correctly.
Curiosly Agrolait started with 4 tasks, and then changed to 5 (you example has zero).

![image](https://user-images.githubusercontent.com/1246629/33375589-4eeac7c0-d502-11e7-9a2c-ca903ef90132.png)
