### ISSUE TITLE
project_timeline drag and drop Task Bug

### ISSUE THREAD

**Issue by BeAntares** [OCA/project#323]
On the project_timeline addon tested on the runbot, every time a task is modified (dragged and dropped or resized) directly on the timeline view it shows this error:
default_interval=default_interval, resource_id=resource.id,
AttributeError: 'bool' object has no attribute 'id'

**Comment by pedrobaeza** [comment]
Version?

**Comment by BeAntares** [comment]
Version 10.0.1.0.0 tested on the runbot

**Comment by pedrobaeza** [comment]
There's a new version of web_timeline in progress. Please check it with that one: https://github.com/OCA/web/pull/735

**Comment by bodedra** [comment]
It seems we can close this issue.
