### ISSUE TITLE
[7.0] analytic_hours_block : missing dependency

### ISSUE THREAD

**Issue by laurentmeuwly** [OCA/project#33]
The addon analytic_hours_block is well installing. But you are not able to use it with standard account_invoice.
In fact, the addon is refering an invoice.department_id, wich does not exist:

```
'department_id': fields.related(
            'invoice_id', 'department_id',
             type='many2one',
             relation='hr.department',
             string='Department',
            store={
                'account.hours.block': (lambda self, cr, uid, ids, c=None: ids,
                                        ['invoice_id'], 10),
                'account.invoice': (_get_invoice, ['department_id'], 10),
            },
             readonly=True),
```

Saving a newly created hours block results in this error:
KeyError: "Field 'department_id' does not exist in object 'browse_record(account.invoice, ...)'"

**Comment by dreispt** [comment]
Yes, that dependency should be removed from here and added by a separate module in https://github.com/OCA/department/,
PRs welcome.

**Comment by LoisRForgeFlow** [comment]
This is solved, let's close it!
