### ISSUE TITLE
[NEW] Project name customizing based on orders

### ISSUE THREAD

**Issue by jokr0815** [OCA/project#331]
Hi,

this is a feature request according to https://odoo-community.org/page/specify 

My idea: 

- If we choose to log timesheets based on orders, the project name is very cryptic, e.g. S0001. It should be possible to change it. 

Please see my issue https://github.com/OCA/hr-timesheet/issues/117 as well, which is closely related to project management.

Kind regards
Jo

**Comment by dreispt** [comment]
Shoudn't that be done manually?
What would you use for the automatic project name?

**Comment by SalahAdDin** [comment]
@dreispt i think for example, for manufacturing, name could be a sequence too.
