### ISSUE TITLE
Task color in Project Timeline

### ISSUE THREAD

**Issue by ndkazu** [OCA/project#342]
Hello, I am trying to change the color of my task according to the task stage, I've noticed that the original color configuration shown below does not seem to be active: 
`<timeline date_start="date_start"
                      date_stop="date_end"
                      default_group_by="project_id"
                      event_open_popup="true"
                      colors="#ec7063: user_id == false; #2ecb71: kanban_state == 'done';"
            </timeline>`

even with a kanban state "done" with task in it the color won't change
What am I doing wrong? how can I fix it?

Kazu

**Comment by pedrobaeza** [comment]
Version?
project_timeline module already includes that colors and it's working correctly.

**Comment by ndkazu** [comment]
Hello, 

I am using the following version 10.0.1.1.0
here is a screenshot using the following code `<?xml version="1.0"?>
<timeline date_start="date_start" date_stop="date_end" date_delay="planned_hours" default_group_by="project_id" event_open_popup="true" colors="#ec7063:user_id==false; red:kanban_state=='Completed';"></timeline>`

![image](https://user-images.githubusercontent.com/33208377/33259431-3d5808e6-d3a0-11e7-9cef-357d5101a300.png)


Kazu

**Comment by ndkazu** [comment]
Hello,
I just checked on the runbot. I thought the tasks with the kanban state 'done' were supposed to be Green, but it's not the case. what is the criteria for the green color?

![image](https://user-images.githubusercontent.com/33208377/33260304-c1a39582-d3a2-11e7-836e-4d36d956de0f.png)

![image](https://user-images.githubusercontent.com/33208377/33260371-f6e774f2-d3a2-11e7-9f30-f73c92043e5b.png)

Kazu

**Comment by ndkazu** [comment]
ok I think I got it. The "kanban_state" is not the reference I want to use. I need the "stage_id" as a reference for the color. then I will get a different color for each stage (Todo-->in Progress-->Review--> Completed) of the task. If you have any Idea...

Ndong

**Comment by pedrobaeza** [comment]
That can be possible without hardcoding stage IDs, sorry.

**Comment by ndkazu** [comment]
Hello,
Sorry but i think you misanderstood my request;I am not an xml specialist, but I am not trying to use stage_ids (which exists), but stage_id.
I can use `default_group_by="stage_id"` in the timeline view and it works well, so I don't understand why the following is not working, `colors="red:stage_id==1"` for example, and the following turns everything in red`colors="red:stage_id!=1"`, proof that stage_id is active and usable. sending a request in psql console even tells me that 1 is a valid value for stage_id, so why? am I the only one to find it strange?
please I need to understand.
Thanks
kazu

**Comment by ndkazu** [comment]
Just FYI, this is what I get from the psql console. 
![image](https://user-images.githubusercontent.com/33208377/33413012-490198d6-d5d2-11e7-8a3d-757489936e64.png)
