### ISSUE TITLE
Setting Project Timeline colors according to Stage name instead of kanban state

### ISSUE THREAD

**Issue by ndkazu** [OCA/project#346]
Hello, 
I found a way to solve this issue, so I am sharing for those interested.
I added the following code in "project_task.py" in the ProjectTask class:
`  stage_name = fields.Char(
		related = 'stage_id.name',
		string = 'Stage Name',
		store = True,
	)`
then I can use stage_name in "project_task_view.xml" to change the color as desired:
` <timeline date_start="date_start"
                      date_stop="date_end"
                      default_group_by="stage_id"
                      event_open_popup="true"
                      colors="#ec7063: user_id == false; #2ecb71: stage_name=='Completed'; #19efff: stage_name=='Review'; #ffc10a: stage_name== 'In Progress'; #ff05fa: stage_name =='ToDo'; red:kaban_state=='blocked';">
            </timeline>`
the resulting view is as below:
![image](https://user-images.githubusercontent.com/33208377/33421155-9089fd52-d5f4-11e7-9005-6555dff5dba5.png)
regards,

Kazu

**Comment by pedrobaeza** [comment]
Don't open a new issue for this, please.

**Comment by ndkazu** [comment]
Just wanted to share the solution...
didn't know where to post it...

Kazu
