### ISSUE TITLE
[11.0][MIG] project_parent

### ISSUE THREAD

**Issue by pmartineznetquest** [OCA/project#355]
Hi!

We wander to know if is planned the migration of the **project_parent** module (yes, we tried to install the v10 one with no luck). As far as we know there is no plan to upgrade it and maybe we can collaborate. 

Thank you in advance!
Pere

**Comment by pedrobaeza** [comment]
Well, just migrate it and make the PR here :wink: It's not so complicated. Collaboration will come on reviews, and when you also collaborate with other reviews as well.

**Comment by pmartineznetquest** [comment]
Perfect, @pedrobaeza!

Added to our roadmap! Hope to finish it soon!

Thank you!

**Comment by AaronHForgeFlow** [comment]
Hi @pmartineznetquest, you can also try project_wbs module https://github.com/OCA/project/pull/307 In this module, the analytic accounts in the project hierarchies are considered WBS components. In this module, the parent project is the project associated to the parent analytic account. This module also provides tools to create a hierarchy and navigate through it.

 PD: All reviews are welcomed :smile:

**Comment by pmartineznetquest** [comment]
Hi, @aheficent! Thank you for the comment. 

Seems that all the functionality is there. I will check it out and review as soon as possible and give you feedback and of course, a review. 

Thank you again!

**Comment by bennals** [comment]
@pmartineznetquest 
I noticed you were considering migrating project_parent or project_wbs to v11.  Is it something you are still planning and do you have a time frame?  I'm about to move to v11 from v8 and need the hierarchical project structure.  I am considering paying someone to do the migration via freelancer or upwork.
@aheficent this might also be relevant to you.
