### ISSUE TITLE
Project Department Categorization unmeet dependency

### ISSUE THREAD

**Issue by Ark74** [OCA/project#362]
Hi!

I was wondering if this is the default behavior for Project Department Categorization
10.0.1.0.0

It requires analytic_base_department which seems to be [deprecated on v9.0](https://github.com/OCA/department)
Would this make the module sort of "incomplete" or is there a way to workaround the installation?

Thanks in advance.
Cheers!

**Comment by 4fuss** [comment]
Hi,
You can find missing dependency in this repository: https://github.com/oca/account-analytic

**Comment by Ark74** [comment]
Thanks i'll try it.
