### ISSUE TITLE
[11.0][project_stage_closed] No "closed" stage flag

### ISSUE THREAD

**Issue by SalahAdDin** [OCA/project#400]
I was testing this module but i can't see it working:
![noclosedstage](https://user-images.githubusercontent.com/5034215/42108529-824c1744-7be3-11e8-9041-77c481bd60af.png)

**Comment by pedrobaeza** [comment]
You have to see the stage in form view.

**Comment by SalahAdDin** [comment]
how?

**Comment by pedrobaeza** [comment]
Read the README

**Comment by SalahAdDin** [comment]
I did read but i don't understand which is the form view.

**Comment by SalahAdDin** [comment]
![nadadenada](https://user-images.githubusercontent.com/5034215/42109039-faf7fdec-7be4-11e8-8e1a-deb989357975.png)
Ok, i can't see it still.

**Comment by pedrobaeza** [comment]
Seriously?

![seleccion_026](https://user-images.githubusercontent.com/7165771/42109135-e99c3f5c-7bdc-11e8-8927-4e8166339d11.png)

**Comment by SalahAdDin** [comment]
Thank you.
