### ISSUE TITLE
project_timeline: not proper order in showing tasks

### ISSUE THREAD

**Issue by ghost** [OCA/project#436]
Dear All,
I suppose my concern is related to the web_timeline module.
Anyway, from my perspective, the timeline view should show on the up-left corner the task with the most recent start date and ... so on.
Currently it is the opposite, so the first task is the latest in the timeline view.
This is to achieve this view more similar to the gantt view.
Regards
claudio

**Comment by pedrobaeza** [comment]
The sorting is performed automatically by the library, and it depends on the visual space taken by the item. We have no special control over this, but it's OK on most cases.
