### ISSUE TITLE
Question: State of migration to v8

### ISSUE THREAD

**Issue by hokkaido** [OCA/project#44]
Hi, are the modules already fully ported to v8 or is there still work to do? Do you need help with the migration effort? We might need them for a client of ours.

Thanks

**Comment by dreispt** [comment]
All the modules at the root of the 8.0 branch have been ported to 8.0.
The modules that haven't been ported yes are kept inside the `__unported__` directory.
By the way, this is so for all the OCA projects.

Right now the most important modules have been ported, and there are only a few left that aren't. But it could be the case that they don't make sense anymore. Still feel free to port them if you believe you really need them.

**Comment by hokkaido** [comment]
Thanks for the reply
