### ISSUE TITLE
[11.0 CE] project_task_material_stock Does not consume materials

### ISSUE THREAD

**Issue by eduardgm** [OCA/project#455]
After installing the module and its dependencies: 

1) I set the settings according to Readme
2) Create a new project 
3) Create the first stage A and de second stage B,selecting "Consume materials" checkbox (only in stage B)
4) Create a new task and I assign a stockable product to materials tab.
5) Move the task from A to B
6) Inside the task, I select the button "Check availability" and then "Consume materials". 

Materials are not consumed and they still in "Ready" state.

Am I doing something wrong or missing any step?

Thank you!

**Comment by HaraldPanten** [comment]
I found the same issue, same workflow as @eduardgm 

Any news?

THX

**Comment by jcarlosmontoya** [comment]
@eduardgm @HaraldPanten Stock move does not create stock move lines related with qty_done,
stock moves must be set quantity done before to transfer

**Comment by jcarlosmontoya** [comment]
A little Fix:
https://github.com/OCA/project/blob/11.0/project_task_material_stock/models/project_task.py#L130
Before  call stock moves _qty_done() method
set quantity_done for each stock move or create stock move lines related

**Comment by jcarlosmontoya** [comment]
Im going to create a PR soon

**Comment by jcarlosmontoya** [comment]
Here it is: https://github.com/OCA/project/pull/456

**Comment by HaraldPanten** [comment]
@jcarlosmontoya thank you for your prompt reply.

I'll have a look and review your PR soon.

We can close that issue, then 👍
