### ISSUE TITLE
[11.0] project_task_material_stock Task get's "blocked" when there's not enough stock available

### ISSUE THREAD

**Issue by HaraldPanten** [OCA/project#459]
Steps to reproduce:

Step 1: I create product A with 10 units of stock available

Step 2: I create a project with 3 stages. Stage 1 (normal),  Stage 2 (Consume material checkbox selected), stage 3 (normal).

Stage 3: I create task T1 and I select 20 units of product A to be consumed.

Stage 4: I move T1 to stage 2.

Stage 5: Click to "Check availability" button.

Results:

Result 1: After clicking "Check availability" all other options disappear; so... I can't re-check availability, unreserve materials, consume just the available stock, etc.

Result 2: Stock moves tab is shown as "Partially available" but I can't apply any changes.

Result 3: I can't move back or forward T1 as message "You can only delete draft moves." is shown.

Result 4: Even if I update the available stock for product A to 200 units, I can't update the available stock for product A in T1.

Expected Results:

I think it should (at least) allow the user to re-check availability or unreserve materials.

What do you think?

Am I doing something wrong?

THX!

**Comment by pedrobaeza** [comment]
Aren't you able to switch to a previous stage and change again to the consume stage?

**Comment by HaraldPanten** [comment]
Hello @pedrobaeza ,

I can't move it back to a previous stage or forward to a future one.

"You can only delete draft moves." it says.

**Comment by pedrobaeza** [comment]
Sorry, I didn't see that part in your original message. Well, it seems a new button is needed for this case for rechecking availability. I have the feeling since a bit that we should create pickings instead of only moves for this module.

**Comment by HaraldPanten** [comment]
No worries 👍 

Delivery pickings you mean, right?

We could probably have a better traceability with this change, as I haven't found (yet) where can user check this stock move is coming from. Task ID, task name or anything else, you know.

Any ideas?

THX

**Comment by HaraldPanten** [comment]
Hi all,

Is anybody taking care of the issues? Or should we open a [FIX] PR?

I'm not sure how does the usual flow works.

THX in advance.

**Comment by pedrobaeza** [comment]
Nobody has expressed the interest in fixing it, so you can handle it.

**Comment by HaraldPanten** [comment]
OK

**Comment by jcarlosmontoya** [comment]
@pedrobaeza I agree with you, this module should create Stock Picking instead stock moves, 
also, I just see that the analytical cost stays at zero when you use the module sale_timesheet (this module always recompute amount in create Analytic lines)
Should i create a new issue?
Should we create a new module with dependency for FIX this issue? (I can do it)

Thank you in advance

**Comment by pedrobaeza** [comment]
@jcarlosmontoya OK, go ahead directly with the PR.

**Comment by HaraldPanten** [comment]
Hi @jcarlosmontoya 

Thanks for your cooperation.

**Comment by jcarlosmontoya** [comment]
@HaraldPanten @pedrobaeza check this module please #462

**Comment by jcarlosmontoya** [comment]
Hello all, I just to add a PR #472 where improve consume materials with picking

**Comment by HaraldPanten** [comment]
Hi all,

That issue was solved in this merged PR.

https://github.com/OCA/project/pull/472

Closing.

Thanks @jcarlosmontoya
