### ISSUE TITLE
Project timeline 12.0

### ISSUE THREAD

**Issue by fietiger** [OCA/project#481]
1. If there are so many Projects or tasks ,no scroll bar on right side.
2.After uninstall,App Project  reports " No default view of type 'timeline' could be found !",and crashed.

**Comment by Nikul-Chaudhary** [comment]
Hello @tarteo , Can you please handle/Fix this issue.

**Comment by tarteo** [comment]
Report this issue here: https://github.com/OCA/web and formulate the issue better (using e.g. a video showing the issue).
