### ISSUE TITLE
[12.0] Cannot see project timeline

### ISSUE THREAD

**Issue by Tisor** [OCA/project#482]
Hi,

I have installed on my Odoo Community 12 the Project Timeline Addon.

My needs are to show a Timeline window, grouped by employee and the projects he is on, so we can check the availability of each employee to assign new projects to.

The problem is I'm not even able to see the default timeline for projects. I know I need to create a new addon myself to create the view I'm requesting. Never done this before, but will be a long way to get it. At least I want to be able to see the timeline view by default.

I don't see the clock button on any project view. I have timeline added in all the Window Actions, but the clock button is not showing.

When I try to open directly from Debug the project.project timeline view from the dashboard or the project.task timeline within a project, no window shows up, not even a error one.

Hope I can get some help on that.

Saludos
Dani.

**Comment by pedrobaeza** [comment]
Sorry, but this is a deployment issue, not a problem on the addon itself. Try on runbot to see that it's working.
