### ISSUE TITLE
[11] When Refreshing (F5) the page we lose place where we were 

### ISSUE THREAD

**Issue by anabeladamas** [OCA/project#483]
In v11 when I refresh the page of the timeline view, I lose the zoom that I had before.

It is possible to change this behavior, and keep the zoom and date where I has before the F5  ?

**Comment by pedrobaeza** [comment]
I'm afraid this is not possible, as that information is not kept in the URL. You shouldn't refresh or use the back button in the browser, but use the breadcrumb or click-through links.

**Comment by pedrobaeza** [comment]
And for refreshing current view, just go to the search bar, and click enter.

**Comment by anabeladamas** [comment]
> And for refreshing current view, just go to the search bar, and click enter.

Good tip, but before I do that I had zoom in and was in May 2019 with the days in  the lower bar, and after "click enter" I see All year . 

Before :   
![image](https://user-images.githubusercontent.com/10194171/54530707-64a74680-497b-11e9-8f0d-e338fcafab8b.png)
After: 
![image](https://user-images.githubusercontent.com/10194171/54530728-7a1c7080-497b-11e9-9873-68fa655a1801.png)

So isn't possible to keep zoom like it was before ?

**Comment by pedrobaeza** [comment]
With current design it's not. What you can do is to filter your view with that date range for forcing the view to be kept there.
