### ISSUE TITLE
[IMP] project_timeline: Timeline view & Subtasks

### ISSUE THREAD

**Issue by emagdalenaC2i** [OCA/project#485]
Currently, the timeline view does not distinguish tasks and subtasks. 
It would be nice to have a filter to show only the parent tasks (without subtasks), as defined in #347 

Also, when accessing the subtasks of a specific task, the timeline view is not available.

**Comment by pedrobaeza** [comment]
I don't think you need a special module. Just do "Subtasks" (or whatever name of the field) "is not set" in your search more in UI.

**Comment by emagdalenaC2i** [comment]
That's what I do rigth now... and I have to do that everytime... 
And no, I can't set that filter as the standard view, because there are always other filters with the name of the project.

Plus, as I mentioned before, the timeline view isn't available if I access to the subtasks of a specific task.
You can search for a set of tasks inside a project, then press the timeline view icon and only that tasks are in the timeline view, but that isn't available for subtasks

**Comment by pedrobaeza** [comment]
I don't get you at all, but if you have it clear, then OK with the module.

**Comment by flotho** [comment]
@emagdalenaC2i 
the point is that the timeline is set up on a specific action and not on all the actions. Reaching subtask from a parent is not the same action as the main one displaying all the tasks with sub kanban view.
as Odoo don't allow inheritance on action for the moment youu'll have to add the timeline as a display mode in each action on tasks if you want to have it everywhere.
regarding the filter, you could create a specific filter as an inheritance oof the main search view and then set it up by default in each action.
this way you won't have to click anymore on your favorite filters.

regards
