### ISSUE TITLE
project_timesheet_time_control: Stop button don't work on task in Odoo 11

### ISSUE THREAD

**Issue by sseerrggii** [OCA/project#497]
Testing module project_timesheet_time_control
Seems like stop button don't save current time. I'm testing it on Odoo 11 CE
![Peek 10-04-2019 19-58](https://user-images.githubusercontent.com/2297137/55902214-525fa780-5bcb-11e9-8a42-04cc97bc1415.gif)

**Comment by rafaelbn** [comment]
Hi @sseerrggii , create the line and save. Work in you task and when you finish click on the stop button. The time spent will be calculated.

**Comment by pedrobaeza** [comment]
Button is not clickable until you save the line. This is not something of the module, but how Odoo framework works: a button inside a one2many line is not clickable for in-memory records.

Closing as no issue.

**Comment by sseerrggii** [comment]
Ok!
It's not very intuitive but :+1:
