### ISSUE TITLE
Can't setup "control date"

### ISSUE THREAD

**Issue by nicolassolop** [OCA/project#50]
Hi, for some reason can't fin the way to setup the "control date" field.

The error is: 

"The following fields are invalid: Model"

I'm working with odoo 8.x.

Can you help me out with this?

**Comment by dreispt** [comment]
Can you provide more details? What values have you tried on the form? Maybe provide a traceback of the error
Thanks.

**Comment by dreispt** [comment]
I'm assuming you found a solution. Closing.
