### ISSUE TITLE
Odoo 11 Allow timesheet always on

### ISSUE THREAD

**Issue by TimvM** [OCA/project#542]
Hello,

Currently the option 'allow_timesheets' is only active at default when a product of a sales order line contains the service policiy: deliverd_timesheet. 

Is it possible to have this option always active?

**Comment by pedrobaeza** [comment]
This is something outside of this repo, so closing.

Quick answer: try to put it as default value.

**Comment by TimvM** [comment]
Already tried that ofcourse..
Doesn't work
