### ISSUE TITLE
[7.0] module 'project_action_item' depends on 'hr_timesheet_task'

### ISSUE THREAD

**Issue by dreispt** [OCA/project#55]
Currently CI build fails because of a missing dependency:

ERROR: "You try to install module 'project_action_item' that depends on module 'hr_timesheet_task'. 
But the latter module is not available in your system."

Is this dependency avoidable?
Otherwise we need add the corresponding repo to the TravisCI config.

**Comment by katyukha** [comment]
[hr_timesheet_task repo](https://github.com/OCA/hr-timesheet/tree/7.0)

**Comment by dreispt** [comment]
Fixed by #55
