### ISSUE TITLE
[RFF] project_key and project_wbs: can sub-projects share key of parent?

### ISSUE THREAD

**Issue by alexey-pelykh** [OCA/project#551]
@ernestotejeda @tarteo @bjeficent @aheficent calling you for hear out your feedback on the matter.

**Comment by AaronHForgeFlow** [comment]
Technically we are not that far. There is a constraint that disallow to have same key in more than one project but it is possible to rewrite it to only consider projects out of its own WBS

**Comment by alexey-pelykh** [comment]
@aheficent thanks for your input, indeed we can adjust `project_key` to have dynamic constraint instead of having SQL one and make extend it in `project_key_wbs`. That module can also address sharing task identifier sequence between projects?

One more question appeared in my mind - for the rest of modules and reports, parent-child projects are going to be different, so for getting any report for "entire project" would require some sort of glue module, right?

**Comment by AaronHForgeFlow** [comment]
@alexey-pelykh  I think so, a dynamic constraint can handle also task sharing.

Regarding the second question, yes, I think a glue module is needed for that kind of integration, what report are you thinking about?

**Comment by alexey-pelykh** [comment]
@aheficent got it! Regarding the reports: e.g. project > overview, I believe it originates from sales_timesheet module

I'm not entirely sure where the line between "standalone project" and "sub-project" should go in terms of:
 * When I select timesheets from Parent project - should I get 0 entries since to timesheets were logged towards that project, or should I get all entries?

**Comment by AaronHForgeFlow** [comment]
In my opinion users should get all entries as long as the parent is the overview of all the entries of the children. Usually, I see that companies only allow to post timesheets on the lowest level in the wbs structure (work packages) and the upper levels are useful to analyze the state of the whole project.

**Comment by alexey-pelykh** [comment]
Agree, any other places that you think it would be useful to change ('project_id','=',...) to `child_of`?

**Comment by AaronHForgeFlow** [comment]
No directly related to projects, but it would be good to see all the purchases for all the sub projects when filtering purchases by parent analytic account. Similar also for stock moves analysis by projects
