### ISSUE TITLE
[12.0] project_template: Comparing apples and oranges

### ISSUE THREAD

**Issue by alexey-pelykh** [OCA/project#564]
https://github.com/OCA/project/blob/c6aab70279523cad1a337e8a2823269db1e1e2fe/project_template/models/project.py#L20

```
2019-08-12 20:25:01,516 5820 WARNING openerp_test odoo.models: Comparing apples and oranges: project.project(135,) == 135
```

**Comment by alexey-pelykh** [comment]
Won't next line cause issues as well?

**Comment by hbrunn** [comment]
no, because of https://github.com/OCA/OCB/blob/12.0/odoo/fields.py#L2137

**Comment by alexey-pelykh** [comment]
oh, good to know!
