### ISSUE TITLE
[12.0] project_template: project.project.create() with unknown fields: total_planned_hours

### ISSUE THREAD

**Issue by alexey-pelykh** [OCA/project#565]
https://github.com/OCA/project/blob/29859a8368f0ec6991b26c2295ce9c4799e09f9a/project_template/models/project.py#L18

**Comment by alexey-pelykh** [comment]
I haven't found this field nor in OCA sources neither in Odoo sources

**Comment by pedrobaeza** [comment]
Well, remove it then.

**Comment by alexey-pelykh** [comment]
Sure :) Just adding it as todo
