### ISSUE TITLE
[7.0][8.0] project_baseuser Missing 'Projects Administrator' group

### ISSUE THREAD

**Issue by JordiBForgeFlow** [OCA/project#59]
@dreispt I'm interested to use this module. However I have the following concerns:
- If the group "Project Manager" can only view the projects they manage, why can they still access to the project configurations settings for all projects?
- Who will then have access to view all projects? I can see that in an organization, directors will need to have access to list all projects.
- In an organization that has a Project Management  Office administrative department, a PMO Project Administrator role would typically have full access to all projects and also Project Configuration, because they provide service to all Project Managers in the organisation.

Would it make sense to add the following changes?
1. Add a new group "Project Administrator", that has full access to all projects + access to the Project Configuration menus.
2. Remove the authorisations to the group "Project Manager" to access to the Project Configuration menus.

Regards,
Jordi.

**Comment by dreispt** [comment]
For my use case, it was OK to use the super admin to manage all projects.
I now realize that the "Project Manager" group is closer to a Project Administrator, but is suiting both roles.

An improved granularity is a nice addition. I agree with you proposed changes. 
:+1:

**Comment by angelapper** [comment]
I tried this on v.8, it dose not work, the rule user_id = user.id did not prevent

**Comment by pedrobaeza** [comment]
Any news on this?

**Comment by rafaelbn** [comment]
Please take a look in: 
- https://github.com/OCA/project/issues/108
- And this PR https://github.com/OCA/project/pull/117

I wish we will finish soon.
