### ISSUE TITLE
[RFC] - Project tasks and calendar events

### ISSUE THREAD

**Issue by sbejaoui** [OCA/project#602]
Hi,

We have a business need to link project tasks and calendar events. Ideally we would like to:

* Have a button in task form view that returns all related events.
* When a user plan an activity of type meeting he can quickly access to this event from the task form view.

I am wondering if there is an OCA module to do this or I can propose it.

**Comment by pedrobaeza** [comment]
I don't know any. I wonder also if it should go to OCA/calendar

**Comment by sbejaoui** [comment]
> I don't know any. I wonder also if it should go to OCA/calendar

calendar event object has `res_id` and `res_model` fields. If they are used the event form show a link to the source document.

![1](https://user-images.githubusercontent.com/12665409/67697320-a33cbf00-f9a8-11e9-92e3-2b9124a23533.jpg)


we can use this two fields to build a mixin that add an action to show linked events and a computed field for the count. this can go to OCA/Calendar repo as a base module.

then in each repo, when it's needed, we create a module that inherit from the base one to add the action to the form view.

What do you think? 

Any inspiration for module/object name?

**Comment by pedrobaeza** [comment]
Sorry, haven't got time for answering you. The name you have put seems OK.

**Comment by sbejaoui** [comment]
I made a PR to OCA/calendar

see: https://github.com/OCA/calendar/pull/12
