### ISSUE TITLE
Project timesheet time control

### ISSUE THREAD

**Issue by erconamule** [OCA/project#605]
Hello!
I wanted to use this addon and discovered a little weirdness):
Start/Stop timer works only for Administrator. And works fine.
If I log in as User, there is a button Start, push Start - have created Task, timer doesn't start.
I know this:
"Note: All the Start/Resume/Stop features are disabled if you don’t belong to the Timesheets/User group or if you are viewing a timesheet that belongs to another user."
And my User is Timesheets/User, and/or Timesheets/Manager, and/or Admin/Setting but it's all not work.
I created a new database but it's not work...
May be I didn't set something or didn't install some... Help Me ;(
Sorry for my English...
V 12.0.2.1.0
Created Views
* INHERIT Add timesheet time controls (form)
* INHERIT Add timesheet time controls (form)
* INHERIT Add timesheet time controls (kanban)
* INHERIT Add timesheet time controls (kanban)
* INHERIT Add timesheet time controls (tree)
* INHERIT Add timesheet time controls (tree)
* INHERIT account.analytic.line tree (tree)
* INHERIT account.analytic.line.form.inherit (form)
* INHERIT account.analytic.line.kanban (kanban)
* INHERIT hr.timesheet.switch resume form (form) 
Dependencies
hr_timesheet_task_stage	Installed
hr_timesheet_task_domain	Installed
web_ir_actions_act_multi	Installed
web_ir_actions_act_view_reload	Installed

**Comment by pedrobaeza** [comment]
It's totally logic that the module requires "Timesheet/User" permission for having that features. The module has `timesheet` in its name because of that.

Closing as no real issue.

**Comment by erconamule** [comment]
Thank you!!!! How to do it? I don't understand. I'm newbie in Odoo. If you please.

**Comment by pedrobaeza** [comment]
Give to your user that permission. How to exactly do that is out of the scope of this issue tracker. Ask in the forums if you are not able to do it.

**Comment by erconamule** [comment]
OK! I did it.

**Comment by pedrobaeza** [comment]
Then everything should work. Try in runbot for seeing the default behavior.
