### ISSUE TITLE
[RFC] Flow Metrics

### ISSUE THREAD

**Issue by mileo** [OCA/project#611]
Hello, we are starting the development of some modules, which are the basis of the principles that we use internally in task management:

**project_wip:** Statistics of how much time each task spends at each stage;

**project_value_stream:** Statistics related to the amount of tasks that enter our work system and leave our work system;

**project_cumulative_flow:** http://brodzinski.com/2013/07/cumulative-flow-diagram.html

**project_wsjf:** https://www.scaledagileframework.com/wsjf/

**project_acd:** Average Cost per Demand ("ACD")

> In order to list at least two variables, one of them necessarily a financial variable, the Average Ticket on Demand (TM) was born, which months later was renamed to Average Cost on Demand (ACD). 
> 
> This metric relates operating cost to throughput, which is the flow rate per unit of time. This relationship has given us a much more robust cash figure that is much more in line with business needs.
> 
> ACD was born to be a comparative metric, so it doesn't matter if in your business you will consider the entire operating cost or just a part.
> 
> What matters here is the maintenance in the way the two metrics that make up the ACD are obtained, knowing that if you change all the history will be lost.
> 
> Let's now explore a simple model:
> 
> Operating Cost: 3 People, $ 30,000.00
> Throughput: 30 demands / month
> ACD = $ 1,000
> 
> One of the team went on vacation in the second month:
> Operating Cost: 2 People, $ 20,000.00
> Throughput: 20 demands / month
> ACD = $ 1,000
> 
> In its composite nature lies the stability of the ACD. If we only follow throughput, we risk making the wrong conclusions about the company's current situation. By crossing important metrics, we get more precision in the analysis and decisions that will emerge. Let's now imagine the opposite scenario:
> 
> Operating Cost: 2 People, $ 20,000.00
> Throughput: 20 demands / month
> ACD = $ 1,000
> 
> The company hired one person:
> Operating Cost: 3 People, $ 30,000.00
> Throughput: 23 demands / month
> ACD = $ 1,304.00
> 
> If we look once again at throughput alone, we can conclude that a 15% increase in deliveries might justify the new person. What could we conclude with a 30% increase in ACD? In addition to being an important decision maker, we can use ACD as a marker for Brooks Law.
> 
> Would it be fair to say that, upon returning to the ACD prior to the new person's entry, this team no longer suffered from the impacts of Brooks Law? Not precisely, because we are in a complex system, but we can come closer with a pragmatic metric.
> Source: https://drive.google.com/file/d/1z013FVhBCznUxHddR49YsxcNKFFRPgzw/view?usp=sharing

We appreciate any suggestions,I didn't find any references in English about Average Cost per Demand, if anyone knows please post here.

**Comment by pedrobaeza** [comment]
@jbeficent you did some work on this, isn't it?

**Comment by mileo** [comment]
@JordiBForgeFlow

**Comment by JordiBForgeFlow** [comment]
@mileo we use earned value management system. See https://www.odoo.com/es_ES/event/odoo-experience-2019-2019-09-30-2019-10-04-1629/track/project-management-with-the-lights-on-earned-value-management-using-odoo-1447

I am not sure about the kpis that @mileo propose here. I guess that I need more detail to understand better.

**Comment by gabrielcardoso21** [comment]
project_wsjf: https://github.com/OCA/project/pull/631
