### ISSUE TITLE
[RFC] project_stock_account

### ISSUE THREAD

**Issue by max3903** [OCA/project#613]
Depends on:
- [ ] https://github.com/OCA/product-attribute/issues/528
- [ ] https://github.com/OCA/stock-logistics-warehouse/issues/765
* project_stock_request

This module allows you to account for the inventory items consumed in a project by:
* invoicing them to the customer or
* expensing them

# Usage

* Go to Projects > Configuration > Projects
* Create or select a project
* Add stock requests to a customer location and process them
* Click on:
  * Invoice to transfer the value to the expense account of the product category/product (Cost Of Good Sold)
  * Expense to transfer the value to the secondary expense account of the product category/product (Expense)

# Technical Specifications

## project.project

- [ ] Add a button "Expense".
- [ ] When clicked, call _expense(partner) on all the done stock requests delivered to a customer location with an empty "Journal Entry" and "Invoice Line" where the partner is the "Customer" of the project.
- [ ] Add a Invoice button.
- [ ] When the project is invoiced (from the project or from the sale order), call _invoice(partner) on all the done stock requests delivered to a customer location with an empty "Journal Entry" and "Invoice Line" where the partner is the "Customer" of the project

**Comment by HaraldPanten** [comment]
Hi @max3903 ,

Maybe this could be added as an improvement of project_task_material_stock https://github.com/OCA/project/pull/572 and allow the user to invoice it separately or keep it added as an expense related to the project.

What do you think?

**Comment by max3903** [comment]
@HaraldPanten We are already using project_stock_request as it better match our use case: the project is a construction project where the project user/manager wants inventory items to be shipped to the customer location by the warehouse team.

project_task_material_stock seems to fit more the use case where the project is internal and the project user is going to the warehouse to pick up what he needs. Am I right?

**Comment by HaraldPanten** [comment]
Hmmm... OK then!
