### ISSUE TITLE
[12.0][BUG] project_template: Error if user delete word "(TEMPLATE)"

### ISSUE THREAD

**Issue by tonihr** [OCA/project#620]
module: project_template
version: 12.0

If a user deletes the word template when marking the project as a template, an assignment error of the variable "new_name" occurs.

![imagen](https://user-images.githubusercontent.com/11601349/70434011-65d95000-1a83-11ea-8143-8807edf910b1.png)

**Steps to reproduce**
    Create a project an mark as a template
    edit name and remove word " (TEMPLATE)"
    Click on create project from template

**Current behavior**
Reference error

**Expected behavior**
Allows custom name in project template.

**Solution**
Add else after new_name assignment

```
if " (TEMPLATE)" in self.name:
            new_name = self.name.replace(" (TEMPLATE)", " (COPY)")
else:
            new_name = self.name +" (COPY)"
```

**Comment by bodedra** [comment]
We can close this PR as a reference of https://github.com/OCA/project/commit/e02fe13b82c1e6ba58dd652477d274c7fe8db94c
