### ISSUE TITLE
[project_category] i18n fr.po translation

### ISSUE THREAD

**Issue by devingfx** [OCA/project#640]
There is a "#, fuzzy" comment on one translation of module project_category this breaks this translation (menu Configuration > Project Type). Poke @gregory-moka ;)
In file https://github.com/OCA/project/blob/12.0/project_category/i18n/fr.po

**Comment by gregory-moka** [comment]
Ok, I translated on weblate, and check this value at "Fuzzy" (à vérifier). It seems the process cause issues in translation file.
I uncheck it, so.. everything should be fine now.

**Comment by devingfx** [comment]
It seems that odoo translation files ( *.po ) are using comments to specify what odoo object/field is translated, so this "fuzzy" comment is breaking the algo for this menu's translation...
I tested localy to remove the "#, fuzzy" part and uninstall/reinstall the module and it worked !

By the way, my odoo instances infrastructure are using direct git sub-module to add OCA addons, and I needed the original repo (here) to be clean to avoid to have to fork myself the entire project repo just for that small thing !

Another thing: I'm french and the translation "Type de projet" is just perfect, you can safely remove the fuzzy tag ;)

Thank you!

**Comment by devingfx** [comment]
I'll wait for bots and other automation to make the change active in my local clone to mark this issue closed...

**Comment by devingfx** [comment]
Ok, I'd got the modification replicated, I can close this issue...

@gregory-moka Dis-moi comment fait-on pour rentrer dans l'équipe de traducteurs d'OCA et avoir les droits en écriture dans le weblate?

**Comment by gregory-moka** [comment]
@devingfx Je t'avoue n'avoir rien fait de spécial, simplement ouvert un compte sur https://translation.odoo-community.org/, déclaré mes préférences de langues dans le profil, et je peux accéder aux traductions.
Tiens moi au courant

**Comment by devingfx** [comment]
Pareil.. mais j'ai un tooltip "Droits insuffisants pour enregistrer les traductions" sur les boutons enregistrer et suggerer sur le formulaire de trad. :/
Après je ne suis pas non plus un contributeur d'odoo sur github... Est-tu autorisé dans github? (savoir si il y a un lien peut-être entre GH et weblate)

**Comment by gregory-moka** [comment]
Non, je ne suis pas contributeur github/odoo.
Ça m'étonnerait aussi qu'il faille être membre pour contribuer aux traductions.. Je t'avoue, je sèche..

C'est peur être un oubli ? : https://docs.weblate.org/en/weblate-3.10/admin/access.html#users-roles-groups-and-permissions

**Comment by devingfx** [comment]
Bon... tant pis je contribuerait plus tard... :/
merci quand même pour ton temps l'ami ! :)
