### ISSUE TITLE
Runbot missing

### ISSUE THREAD

**Issue by lfreeke** [OCA/project#652]
I notice that the latest pull request don't have runbot available.  

see for example :
https://github.com/OCA/project/pull/646
https://github.com/OCA/project/pull/650
https://github.com/OCA/project/pull/645

**Comment by emagdalenaC2i** [comment]
The same happens here https://github.com/OCA/stock-logistics-reporting/pull/91

**Comment by emagdalenaC2i** [comment]
@OCA/project-service-maintainers are there any issues with runbot?

**Comment by gurneyalex** [comment]
There may be, I triggered an update of the builds manually across all the repositories.

I'll monitor what's happening and why this is not happening automatically

**Comment by emagdalenaC2i** [comment]
Ok, seems it is fixed now in these PR

**Comment by lfreeke** [comment]
It seems to be working again. Thank you @gurneyalex  

I will close the issue.
