### ISSUE TITLE
[12][FIX] project_task_add_very_high, project_template: 12.0.1.0.1 not available

### ISSUE THREAD

**Issue by skeller1** [OCA/project#669]
project_template and project_task_add_very_high are not not available as download on https://odoo-community.org/ or https://apps.odoo.com

- project_task_add_very_high: 12.0.1.0.1 not available after #513  
- project_task_add_very_high: 12.0.1.0.1 not available after #627

Could somebody please explain the reasons (blocking addons, revert, deployment errors)
The improvements in these PR are needed.

Thank you

**Comment by pedrobaeza** [comment]
@sbidoul what is the frequency for OCA apps store update? Maybe there is an error blocking the update?

**Comment by skeller1** [comment]
Is it possible to running the pipeline (ocabot merge command) again?

**Comment by skeller1** [comment]
Both addons are available in latest version.

**Comment by sbidoul** [comment]
We recently identified that an incorrect `development_status` key in one manifest in a repo was blocking the app store sync.
Until https://github.com/OCA/maintainer-quality-tools/issues/679 is done, please check them carefully manually.
