### ISSUE TITLE
[IMP] Tasks classification

### ISSUE THREAD

**Issue by aitalinassim** [OCA/project#676]
**Impacted versions:**
master

**Feature this functionality:**
Integration of a new feature to improve module functionality and user experience.

**Current behavior:**
Only given kanban or list view of tasks, without classification possibility.
Only star given tasks are shown on the top.

**Desired behavior:**
Allow the user to class the tasks on 4 principle classes:

_To do immediately
to do later
to delegate
not to do_

This classification will be made as per each task, when the user enter the task, he gives "IMPORTANCE" note and "EMERGENCY" note.

Tasks will be classified as per the following.

![urgency-importance-matrix](https://user-images.githubusercontent.com/28365138/82685031-78b79980-9c4b-11ea-9edf-277937827a06.png)

**Comment by pedrobaeza** [comment]
What about the module I have mentioned in the other issue? It's a similar concept. You know that there are lots of similar project methodologies.
