### ISSUE TITLE
[12][BUG] project_timesheet_time_control previous date field in form view

### ISSUE THREAD

**Issue by js-landoo** [OCA/project#677]
Hi.
We are using this module, it's really nice, thanks for your work.
We have noticed a small bug but with important consecuences.
List view project_timesheet_time_control.account_analytic_line_tree changes core "date" field by new date_time field, this is OK.
But if we use group  filter in list view, create button opens form view and then old field "date" is used. So if user enters a timesheet, both date can be different and user doesn't notice.

Proposed solution: just change date field in form view.

If you want, we can do it in a PR.
I wait for your news.
Regards.

**Comment by pedrobaeza** [comment]
OK, weird use you do, but no problem in switching that field. Hide the `date` one (not replace it), and add the other. Are you sure the form view is the standard one in the dependency chain?

**Comment by js-landoo** [comment]
Hi @pedrobaeza 

Yes, maybe a bit strange use, but grouping data is quite usual and form view is Odoo standard behaviour in this case.

I've checked views and I see Enterprise maybe uses a different form view (different xmlid, but same name). So maybe this fix will not solve our problem.

Nevertheless in Community, you have same bug:
hr_timesheet.hr_timesheet_line_tree, field switched
hr_timesheet.hr_timesheet_line_form, account.analytic.line.form, field NOT switched

Enterprise
hr_timesheet.hr_timesheet_line_tree, same view, field switched
timesheet_grid.timesheet_view_form, account.analytic.line.form, field NOT switched

What do you suggest?

**Comment by pedrobaeza** [comment]
You need to:

- In `project_timesheet_time_control`, switch the field in hr_timesheet.hr_timesheet_line_form, account.analytic.line.form
- See if in enterprise it's solved also. If not, you will need a glue module `project_timesheet_time_control_enterprise` depending on both for adding the switch.
