### ISSUE TITLE
[12.0] project_timesheet_time_control: incompatible with sale_timesheet_rounded

### ISSUE THREAD

**Issue by j-zaballa** [OCA/project#687]
project_timesheet_time_control makes a call to `read` method and passes a `odict_keys` type fields parameter instead of a `list`:

- https://github.com/OCA/project/blob/12.0/project_timesheet_time_control/wizards/hr_timesheet_switch.py#L126

(Because `<model>._fields` is an OrderedDict: see [here](https://github.com/OCA/OCB/blob/13.0/odoo/models.py#L2645)).

On the other hand, sale_timesheet_rounded makes a call to `copy` on fields parameter inside `read`, assuming that the parameter is a list:

- https://github.com/OCA/timesheet/blob/12.0/sale_timesheet_rounded/models/account_analytic_line.py#L149

I would say that the solution is to cast fields before the call in project_timesheet_time_control:

`_fields = list(self.env["account.analytic.line"]._fields.keys())`
or
`self.read(_fields)`

**Comment by pedrobaeza** [comment]
The incorrect one is `sale_timesheet_rounded` that should be aware of the different ways that `fields` can pass. What about doing there?:

```python
fields_local = list(fields) if fields else []
```

**Comment by enriquemartin** [comment]
> 
> 
> The incorrect one is `sale_timesheet_rounded` that should be aware of the different ways that `fields` can pass. What about doing there?:
> 
> ```python
> fields_local = list(fields) if fields else []
> ```

done!
