### ISSUE TITLE
[12][BUG] incompatibility on Project Key vs Project Template

### ISSUE THREAD

**Issue by JordiADARIA** [OCA/project#693]
If you installs Project template on an instance with Project key installed, you can create project templates, but you can not create project from template, because you get "**project key must be unique**" error. 

it seems it is creating a project from template getting "the same" project key.

anybody knows how to solve it?

**Comment by HaraldPanten** [comment]
Hi @JordiADARIA ,

I mentioned this, when the migration to V13. It seems that it's a known issue that has been inherited version by version. You can have a look at the comments here: https://github.com/OCA/project/pull/684

Even though, if you create an interesting PR for improving it's performance, I'll be happy to review it.

Regards,

**Comment by JordiADARIA** [comment]
Hi Harald,

yes, youre right, and i understand the functional enviroment..., i think the issue could be closed, because its not a real "bug", but only perhaps a possible improvement..

thanks for your help!
