### ISSUE TITLE
[12.0] project_task_code - "ERROR: null value in column "code" violates not-null constraint" via api/xmlrpc create

### ISSUE THREAD

**Issue by KJAgit** [OCA/project#694]
When creating a new project.task record via API/xmlrpc, the module fails to generate a new sequential "code" and logs a "ERROR: null value in column "code" violates not-null constraint" message.

Via web module creates new tasks/code sequence fine.

FYI:  I'm using a very similar api call with the crm_lead_code module and it works fine and generates a new sequential code as expected.

**Comment by AaronHForgeFlow** [comment]
It seems you have to adapt your script to include that field.

**Comment by ghost** [comment]
Can you show me how you made the creation script

**Comment by KJAgit** [comment]
I probably should have also mentioned that I'm using this internally and calling the api via vbscript using the aspxmlrpc connector:
http://whatsnewjack.blogspot.com/2014/05/how-to-access-openerp-xmlrpc-service.html

The part of the code i'm using to run the create task call is:

```
Dim taskdata
set taskdata= Server.CreateObject("Scripting.Dictionary")
taskdata.Add "name",""& frmTaskname &""
taskdata.Add "partner_id", frmPartnerid
taskdata.Add "stage_id",1
taskdata.Add "user_id",2
taskdata.Add "date_start",""& frmDatestart &""
taskdata.Add "date_end",""& frmDateend &""
taskdata.Add "project_id", 7
taskdata.Add "company_id", 2
taskdata.Add "description",""& frmDescription &""

Dim newTaskId
newTaskId=Create("http://localhost:8069/xmlrpc/object",dbname,userId,password,"project.task",taskdata)
Response.Write("Task ID: "+CStr(newTaskId)+"<br/>")

Dim ReadNewTask
ReadNewTask= Read("http://locahost:8069/xmlrpc/object",dbname,userId,password,"project.task",Array(newTaskId),Array("code"))
Response.Write("code: "+CStr(ReadNewTask(0)("code"))+"<br/>")
```

Like I mentioned in original post, using this same call (with different model and fields of course) works fine with the crm_lead_code by OCA



> It seems you have to adapt your script to include that field.

I do have the ability to manually add code, but how would I read the next "sequence" number before calling the create?

**Comment by KJAgit** [comment]
This issue does not seem to be code/module related, it was a multi company/user company assignment issue
