### ISSUE TITLE
[RFC] project_earned_value

### ISSUE THREAD

**Issue by max3903** [OCA/project#696]
# Description

This module adds measures to the Task Analysis report and provides a basic [Earned Value Analysis](https://en.wikipedia.org/w/index.php?title=Earned_Value_Analysis&redirect=no) on the project overview.

The additional measures are:

* Planned Value: Initial estimate x unit price of the related sale order line
* Earned Value: Initial estimate x EV % of the stage x unit price of the related sale order line
* Actual Cost: Total Worked Hours x Hourly Cost of the employee
* Schedule Variance: Planned Value - Earned Value
* Cost Variance: Earned Value - Actual Cost

# Configuration

* Go to Project > Configuration > Stages
* Set the earned value percentage for each stage

# Usage

* Go to Project
* Click on Overview to get the earned value analysis of a project

![Screenshot from 2020-08-05 18-08-26](https://user-images.githubusercontent.com/939952/89472761-c457ea80-d746-11ea-9acd-7d5490266cc3.png)

* Go to Project > Reporting > Task Analysis
* Select Planned Value, Earned Value, Actual Cost, Schedule Variance and Cost Variance.

# Technical Specifications

## project.stage

- [ ] Add an integer field "Earned Value %" (ev_percent). Default is 0.

## project overview

- [ ] Add the Earned Value Analysis table

## report.project.task.user

- [ ] Add the following measures to the pivot view:

* Planned Value: Initial estimate x unit price of the related sale order line
* Earned Value: Initial estimate x EV % of the stage x unit price of the related sale order line
* Actual Cost: Total Worked Hours x Hourly Cost of the Employee
* Schedule Variance: Planned Value - Earned Value
* Cost Variance: Earned Value - Actual Cost

**Comment by dreispt** [comment]
@max3903 @Khalid-SerpentCS
From my review, for accuracy the billed time and amount data should be retrieved from Analytic Lines.
Also, consider that not all Analytic Lines are billed to the customer. To know which ones are, check for non empty values on the `so_line` field.
