### ISSUE TITLE
remove project_timeline

### ISSUE THREAD

**Issue by gamestart** [OCA/project#707]
https://github.com/OCA/project/issues/706?notification_referrer_id=MDE4Ok5vdGlmaWNhdGlvblRocmVhZDExMTY1NjMxMzA6OTg2MTk3OQ%3D%3D#issuecomment-686304828

@pedrobaeza

it didn't work, i stoped the container and then start it.

as follow ,the error code 
```
No default view of type 'timeline' could be found !

http://localhost:8069/web/static/src/js/chrome/action_manager_act_window.js:355:41
forEach@http://localhost:8069/web/static/lib/underscore/underscore.js:145:17
_generateActionViews@http://localhost:8069/web/static/src/js/chrome/action_manager_act_window.js:353:15
http://localhost:8069/web/static/src/js/chrome/action_manager_act_window.js:258:50
promiseReactionJob@[native code]
```

maybe the app changed the main page when installed ,but didn't change it back after uninstalled?

**Comment by pedrobaeza** [comment]
Have you updated the DB, specifically `project` module?

**Comment by gamestart** [comment]
no , so could you tell me how to update the DB ?

**Comment by gamestart** [comment]
yes , specifically `project` module , so could you tell me how to update the DB ?

**Comment by pedrobaeza** [comment]
Press on "Update" button on that module, or do it via command line.

**Comment by gamestart** [comment]
Thanks , it worked.

**Comment by gamestart** [comment]
Thanks , it worked .
