### ISSUE TITLE
[13][project_category] Relevance to have "type_id" field with copy set to False

### ISSUE THREAD

**Issue by ygol** [OCA/project#728]
It seem odd that the new field "type_id" gets flagged "copy=False". 
Is this on purpose and what is then the logic?

I would think that it should be copied. 
In this use case, the user prepare a project template that is used by a service's product to generate new projects (one per SO).
The user expects to have these project's type already set as in the template.

Tnx.

**Comment by skeller1** [comment]
> It seem odd that the new field "type_id" gets flagged "copy=False".
> Is this on purpose and what is then the logic?
> 
> I would think that it should be copied.
> In this use case, the user prepare a project template that is used by a service's product to generate new projects (one per SO).
> The user expects to have these project's type already set as in the template.
> 
> Tnx.

I think so, too :+1:
