### ISSUE TITLE
Installation support from command line

### ISSUE THREAD

**Issue by abh23** [OCA/project#736]
Hey there, 
I am trying to install OCA for Odoo 13 via command line. I tried installing modules using odoo-bin script but since by default developer mode is not enabled in Odoo, the modules din't show up anywhere. I tried for project_hr module specifically. 

Is there a way I can enable developer mode via command line using odoo-bin or some other way and then install the OCA module? 

Looking forward for some pointers on this.

**Comment by dreispt** [comment]
Hello, not the best venue for Odoo installation help. I sugguest looking at https://www.odoo.com/forum/help-1
You may also want to look for an Odoo installation guide, there are plenty in the web.

Thanks
