### ISSUE TITLE
project_task_default_stage: resets Stage names

### ISSUE THREAD

**Issue by dreispt** [OCA/project#769]
If the default stage names were changed, installing `project_task_default_stage` resets them to the original names.
This shouldn't be so.

**Comment by skeller1** [comment]
Could you please provide more information to reproduce this bug? Can't reproduce it on `V12`,`V13` and `V14`.
The addon is providing new stages (project_data.xml) and the xml file has `noupdate=1` attribute.

The default odoo project addon stages are also unchanged after installing/updating `project_task_default_stage`.

Thank you
