### ISSUE TITLE
[13.0] field "date_start" doesn't exist anymore in project_timeline  

### ISSUE THREAD

**Issue by javovelez** [OCA/project#774]
Field "date_start" dosn't exist anymore. This field appears to have been replaced by "date_assing" but this one is not editable. 
When a user want schedule a task to start on a specific date , they cannot.  The "date_assign" field is automatically set with the date corresponding to the moment in which the task is assigned to a user

**Comment by javovelez** [comment]
Odoo11:
<img width="576" alt="odoo11" src="https://user-images.githubusercontent.com/18739014/103686794-1c04b700-4f6e-11eb-9ace-8722b9f1bd6a.png">
Odoo13:
<img width="565" alt="odoo13" src="https://user-images.githubusercontent.com/18739014/103686789-1ad38a00-4f6e-11eb-80bf-425751876ae5.png">

**Comment by pedrobaeza** [comment]
Please do a PR amending this.

**Comment by dreispt** [comment]
👍🏼

**Comment by dreispt** [comment]
See https://github.com/OCA/project/pull/801
