### ISSUE TITLE
[13.0] project_timeline scroll doesn't work

### ISSUE THREAD

**Issue by anabeladamas** [OCA/project#804]
I used to have this module in odoo v11 , and to zoom in I used to use the scroll of my mouse. 
In version 13 the scroll alone doesn't work, I've to click in "Ctrl" + Scroll.

**Comment by pedrobaeza** [comment]
Yes, it's a change of the library itself, for not having undesired changes of zooms.

**Comment by anabeladamas** [comment]
So it's a choice ?! 
Ok, thanks for the reply.

**Comment by pedrobaeza** [comment]
Not, it's how it works now.
