### ISSUE TITLE
[13.0][BUG] project_hr - does not show users in kanban quick create form

### ISSUE THREAD

**Issue by vbezl** [OCA/project#831]
Tested on OCA runbot: http://3490049-13-0-8106c4.runbot2-3.odoo-community.org/web

Hi everyone,
If you use quick create option from kanban view - it shows empty list of users:
![Screen Shot 2021-07-05 at 7 00 53 PM](https://user-images.githubusercontent.com/6523179/124497454-8aaeba00-ddc3-11eb-9086-3022658f8a8f.png)

If you then go to the same task and edit it - you can see all users:
![Screen Shot 2021-07-05 at 7 01 18 PM](https://user-images.githubusercontent.com/6523179/124497500-969a7c00-ddc3-11eb-81ef-73f3b87a5fcb.png)

I've debugged it a little and found out that for some reason, the function _compute_allowed_user_ids() is not called when you use quick create in kanban view. Hope this helps to fix the issue asap.

Thank you!

**Comment by leemannd** [comment]
The linked PR is beeing merged

**Comment by leemannd** [comment]
Closing it as a fix has been merged
