### ISSUE TITLE
SLA Issue creating "control date"

### ISSUE THREAD

**Issue by davidberardozzi** [OCA/project#85]
Hi,

Thank you for this great work. I am having trouble creating the "control date" at first setup of a new SLA.
As I can understand, this seems to be the exact same problem that the one reported in this issue : Can't setup "control date" #50.

To create a new SLA, I went throught these steps : 
- Creating a project and working hours
  -Go to its analytic account form
  -In SLA part, when modifying, click on add new item
  -Then click on create
  -On the SLA form there is a "Control Date" field that is empty. When creating a new entry with all mandatory field fullfilled, click on save button leads to an error (popup) saying that the field "model" is invalid.

This field is not alterable.

I am sure I get there using the wrong path, but I cannot find another way. 

I am using V8

Thank you for your kind response.

**Comment by dreispt** [comment]
The `control_model` field looks editable here:

![snap 2015-05-08 at 17 16 16](https://cloud.githubusercontent.com/assets/1246629/7540480/fdbf7140-f5a5-11e4-9674-26abc92e4176.png)

**Comment by davidberardozzi** [comment]
Thank you for your answer and your time.

In fact I misunderstood the way I should use the "For documents" field.

**Comment by dreispt** [comment]
I see, and you're not the first one.
Probably it should be best to change it to a selection field.
