### ISSUE TITLE
project/project_status fails to upgrade on odoo.sh due to "post-migration file must have a migrate(cr, installed_version)"

### ISSUE THREAD

**Issue by azkatech** [OCA/project#850]
Upgrading the project_status on Odoo.sh version 13 gives the error  below and abort the upgrade
This is due to the usage of openupgrade.migrate annotation

module project_status: Each post-migration file must have a "migrate(cr, installed_version)" function

**Comment by pedrobaeza** [comment]
You need openupgradelib.

**Comment by azkatech** [comment]
It is already installed thus not a package issue. Instead the annotation before the migrate is causing this issue on Odoo.sh

**Comment by pedrobaeza** [comment]
Then odoo.sh is not compatible with this way of working. Report it to odoo.sh.
