### ISSUE TITLE
Unassigned area takes so much space

### ISSUE THREAD

**Issue by hitrosol** [OCA/project#852]
I found the unassigned area takes to much space in the timeline view

![image](https://user-images.githubusercontent.com/5949936/131463800-e8b017c0-38e6-44bd-b2ec-4240a44e623a.png)

In fact, none of the task can be placed here because the project field in the Task Form is mandatory.

If I clear out the value in the field "assigned to" in the task form, the color of the timeline change to red, I think it is supposed to moved to assigned area, I guess ? Not sure, maybe I set it in appropriate ?

**Comment by zektul** [comment]
Any plan to fix this? Im having the same issue.

**Comment by pedrobaeza** [comment]
But is this an issue? I think it takes the rest of the reamining space.

**Comment by zektul** [comment]
In our session this is just empty space, even if no projects are unassigned. Would sense to me to display unassigned projects at the bottom of the page.
