### ISSUE TITLE
All tasks window not open

### ISSUE THREAD

**Issue by peterdovicovic** [OCA/project#879]
## Module
Project/project_timeline

## Describe the bug
After installing web_timeline and project_timeline modules in project app menu "Tasks" is not working. There is general error "No default view of type 'gantt' could be found !" . 

## To Reproduce
**Affected versions**: 14

1. Install Project, web_timeline,project_timeline
2.click  Project/Tasks

**Expected behavior**
I expect all tasks window is opened.

**Additional context**
odoo 14 community version with postgress 13.

**Comment by pedrobaeza** [comment]
It seems you have a mix of things, as `gantt` view is not defined in these modules. Please check it with a fresh DB.

Closing as no module issue.
