### ISSUE TITLE
Reapply

### ISSUE THREAD

**Issue by aitorbouzas** [OCA/project#93]
Is there a way to reapply a newly created SLA to old issues in a project? There's no "Service Level" tab into the old issues... I need to apply the SLA's to these issues.

Thanks for your great work.

EDIT:

Just saw that after a change in an issue the new tab appears, but it would be better to have them all applied without making any change... Thanks in advice.

**Comment by dreispt** [comment]
If I recall correctly you do have a "Reapply" buttons on the Project's related Analytic Account and on the SLA form.

The thing is it is not working because of a bug. There is already a fix for it, #83, but it waiting for reviews to be merged.
