### ISSUE TITLE
Change start_date calculation

### ISSUE THREAD

**Issue by aitorbouzas** [OCA/project#94]
I'm just wondering if I can change the initial date that makes the hours calculation (by default is doc.start_date) because our employees, sometimes, create the issues after resolving it but filling in a datetime field called "Issue started at". I'd like to change the initial date to that field...

By just making this change into the project_sla/project_sla_control.py would it be possible (line 198)?:

```
start_date = dt.strptime(doc.[my_date], DT_FMT)
```

Would I need to make any other change to achieve this?

Thanks

**Comment by aitorbouzas** [comment]
Just tried it, maybe we could add a new field to select which start_date we want for the SLA's computation? I think it's a nice idea.

**Comment by pedrobaeza** [comment]
@Softdil, are you going to work on this in a PR? If not, we can close this issue, and maybe include the enhancement in the README's roadmap of the module.

**Comment by aitorbouzas** [comment]
You can close this issue by now. Thank you.
